[tool.poetry]
name = "securitas"
version = "0.0.1"
description = "Securitas is a self-service portal for FreeIPA. The primary purpose of the portal is to allow users to sign up and manage their account information and group membership."

license = "MIT"

authors = [
    "Fedora Infrastructure <admin@fedoraproject.org>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/fedora-infra/securitas"
homepage = "https://github.com/fedora-infra/securitas"

keywords = ['security']

[tool.poetry.dependencies]
python = "^3.6"
cryptography = "^2.8"
flask = "^1.1"
flask-wtf = "^0.14"
python-freeipa = "^0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
pytest-cov = "^2.8"
sphinx = "^2.3"
mock = "^3.0"
beautifulsoup4 = "^4.8"
vcrpy = "^4.0"
pytest-vcr = "^1.0"

[tool.black]
skip-string-normalization = true

[tool.towncrier]
package = "securitas"
filename = "docs/release_notes.rst"
directory = "news/"
title_format = "v{version}"
issue_format = "{issue}"
template = "news/_template.rst"
underlines = "=^-"
wrap = true
all_bullets = true

  [[tool.towncrier.type]]
  directory = "bic"
  name = "Backwards Incompatible Changes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "dependency"
  name = "Dependency Changes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "feature"
  name = "Features"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "bug"
  name = "Bug Fixes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "dev"
  name = "Development Improvements"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "docs"
  name = "Documentation Improvements"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "other"
  name = "Other Changes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "author"
  name = "Contributors"
  showcontent = true


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"